[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'sdl-x'
version = '0.1.0'
description = 'a deep learning library for practice'
authors = [{name = 'huhuang03'}]
dependencies = ['numpy']

[project.dev-dependencies]
pytest = '^7.0.0'